[project]
name = "rr-mcp-server"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "fastmcp>=2.13.0",
    "loguru>=0.7.3",
    "pydantic>=2.12.3",
    "pygdbmi>=0.11.0.0",
]
